---
- hosts: server1
  become: true
  remote_user: admin
  tasks:
  - name: Download jboss 7.4
    ansible.builtin.get_url:
      url: https://software-installers-dc.s3.us-west-2.amazonaws.com/jboss-eap-7.4.0.zip
      dest: /home/admin/jboss-eap-7.4.0.zip
  - name: Unzip jboss-eap-7.4.0.zip
    ansible.builtin.unarchive:
      src: /home/admin/jboss-eap-7.4.0.zip
      dest: /home/admin/
      remote_src: yes
  - name: Crear usuario
    command: /home/admin/jboss-eap-7.4/bin/add-user.sh -u 'admin' -p 'admin'