---
- hosts: server1
  become: true
  remote_user: admin
  tasks:
  - name: Install java 17
    apt:
      name: openjdk-17-jdk
      state: present

    - name: Install unzip
    apt:
      name: unzip
      state: latest