---
- hosts: server1
  become: true
  remote_user: admin
  tasks:
    - name: Descargar Java 17 desde la fuente oficial
      get_url:
        url: "https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_linux-x64_bin.tar.gz"
        dest: /tmp/openjdk-17_linux-x64_bin.tar.gz

    - name: Extraer Java 17
      ansible.builtin.unarchive:
        src: /tmp/openjdk-17_linux-x64_bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: Configurar las variables de entorno para Java 17
      ansible.builtin.lineinfile:
        dest: /etc/profile.d/java.sh
        line: |
          export JAVA_HOME=/opt/jdk-17
          export PATH=$JAVA_HOME/bin:$PATH